### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by naibaf0** [naibaf0/dotfiles#1]
- [x] switch to [zim](/Eriner/zim)
- [x] improve install script
- [x] fix update process
- [ ] write Readme
- [x] evaluate vim plugins, are they all necessary?
- [x] add ycm compileflags symlink file

**Comment by naibaf0** [comment]
many vim plugins removed to be usable on remote server, added neovim
